learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.urls import path
from.import views

app_name = 'learning_logs'
urlpatterns = [
    #Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from.import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    class Status(models.TextChoices):
        DRAFT = "DRAFT"
        PUBLISHED = "PUBLISHED"

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique_for_date="date_added")
    body = models.TextField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.DRAFT)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        return f"{self.text[:50]}"

learning_logs/forms.py
from django import forms

from.models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        lables = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': '3апись:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from.models import Topic, Entry
from.forms import TopicForm, EntryForm
from images.forms import ImageFormSet
from images.models import Image


# Create your views here.


def index(request):
    """Домашняя страница приложения Learning_Log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список тем."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        #Данные не отправлялись; создаётся пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if request.method !='POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
        images_forms = ImageFormSet()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        images_forms = ImageFormSet(request.POST, request.FILES)
        if form.is_valid() and images_forms.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()

            images = images_forms.save(commit=False)
            for image in images:
                image.entry = new_entry
            Image.objects.bulk_create(images)
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form, 'images_forms': images_forms}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
        images_forms = ImageFormSet(queryset=entry.images.all())
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        images_forms = ImageFormSet(
            queryset=entry.images.all(),
            data=request.POST,
            files=request.FILES
        )
        if form.is_valid() and images_forms.is_valid():
            entry = form.save()
            images = images_forms.save(commit=False)
            new_images = []
            for image in images:
                if not image.pk:
                    image.entry = entry
                    new_images.append(image)
                else:
                    image.save()
            Image.objects.bulk_create(new_images)
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form, 'images_forms': images_forms}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static "css/learning_logs/base.css" %}" rel="stylesheet" type="text/css">
  </head>
<body>
  <header class='header'>
    <ul class='header__list'>
      <img class="header__logo" src="/static/LL.png" alt="logo">
      <li class='header__list__item'><a class='header__list__link' href="{% url 'learning_logs:index' %}">/ Журнал /</a></li>
      <li class='header__list__item'><a class='header__list__link' href="{% url 'learning_logs:topics' %}">/ Темы /</a></li>
      {% if user.is_authenticated %}
        <li><p class='auth-user'> / Привет, {{ user.username }} /</p><li>
        <li class='header__list__item'><a class='header__list__link' href="{% url 'users:logout' %}">/ Выйти /</a></li>
      {% else %}
        <li class='header__list__item'><a class='header__list__link' href="{% url 'users:register' %}">/ Зарегистрироваться /</a></li>
        <li class='header__list__item'><a class='header__list__link' href="{% url 'users:login' %}">/ Войти /</a></li>
      {% endif %}
    </ul>
  </header>
</body>
</html>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static "css/learning_logs/edit_entry.css" %}" rel="stylesheet" type="text/css">
  </head>
  <body>
    <ul class="list">
      <li class="list__item"><p class="list__item_paragraph"><a class="list__link" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p></li>
      <hr class="line" size=2px width=1920px color="#666666">
      <li class="list__item"><p class="list__item__paragraph">Изменить запись:</p></li>
      <li class="list__item">
          <form class="list__item__form" action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
          {{ images_forms.management_form }}
            {% for image_form in images_forms %}
              {{ image_form.as_p }}
              {% if images_forms.can_delete %}
                <div>{{ image_form.DELETE }}</div>
              {% endif %}
            {% endfor %}
        <div class="list__item"><button class="button">Сохранить изменения.</button></div>
          </form>
      </li>
    </ul>
  </body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static "css/learning_logs/index.css" %}" rel="stylesheet" type="text/css">
  </head>
<body>
  <p class='index'>/ Это сайт,подобие онлайн-журнала,материалы которого состоят из текста,заметок,изображения. /</p>
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static "css/learning_logs/new_entry.css" %}" rel="stylesheet" type="text/css">
  </head>
  <body>
    <ul class="list">
      <li class="list__item"><p class="list__item_paragraph"><a class="list__link" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p></li>
      <hr class="line" size=2px width=1920px color="#666666">
      <li class="list__item"><p class="list__item_paragraph">Добавить новую запись:</p></li>
        <li class="list__item">
            <form class="list__item__form" action="{% url 'learning_logs:new_entry' topic.id %}" method='post'
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {{ images_forms.management_form }}
                {% for image_form in images_forms %}
                    {{ image_form.as_p }}
                    {% if images_forms.can_delete %}
                        <div>{{ image_form.DELETE }}</div>
                    {% endif %}
                {% endfor %}
                <div class="list__item">
                    <button class="button" type="submit">Добавить запись.</button>
                </div>
            </form>
        </li>
    </ul>
  </body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static "css/learning_logs/new_topic.css" %}" rel="stylesheet" type="text/css">
    </head>
<body>
<p class='new__theme'>Добавить новую тему:</p>
<hr class="line" size=1px width=1920px color="#666666">
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button">Добавить тему.</button>
</form>
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static "css/learning_logs/topic.css" %}" rel="stylesheet" type="text/css">
    </head>
<body>
    <ul class="list">
        <li class="list__item"><p class="list__item__paragraph-1">Тема: {{ topic }}</p></li>
        <hr class="line" size=2px width=1920px color="#666666">
        <li class="list__item"><p class="list__item__paragraph">Записи:</p></li>
        <p class="list__item__paragraph">
            <form action="{% url 'learning_logs:new_entry' topic.id %}" method="GET">
                <button class='button'>Добавьте новую запись темы:</button>
            </form>
        </p>
        <ul class="list">
            {% for entry in entries %}
                <li class="list__item">
                    <li class="list__item"><p class="list__item__paragraph">{{ entry.date_added|date:'M d, Y H:i' }}</p></li>
                    <hr class="line" size=2px width=1920px color="#666666">
                    <li class="list__item"><p class="list__item__paragraph">{{ entry.text|linebreaks }}</p></li>
                    <ul class="list">
                        {% for image_item in entry.images.all %}
                            <li class="list__item"><img src="{{ image_item.image.url }}" alt="{{ entry.text}}" width="500px"></li>
                        {% endfor %}
                    </ul>
                    <p class="list__item__paragraph">
                        <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="GET">
                            <button class='button'>Изменить запись:</button>
                        </form>
                    </p>
                </li>
            {% empty %}
                <p class="list__item__paragraph">В этой теме пока нет записей.</p>
            {% endfor %}
        </ul>
    </ul>
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static "css/learning_logs/topics.css" %}" rel="stylesheet" type="text/css">
  </head>
<body>
  <h1 class='theme'>Темы:</h1>
  <hr class="line" size=1px width=1920px color="#666666">
  <ol class='theme__list'>
    {% for topic in topics %}
      <li class='theme__list__item'>
        <a class='theme__list__link' href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
        <li class='theme__list__item'>Темы еще не добавлены.</li>
    {% endfor %}
  </ol>
  <form action="{% url 'learning_logs:new_topic' %}" method="GET">
    <button class='button'>Добавить новую тему:</button>
  </form>
{% endblock content %}
</body>
</html>